apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-echo-golang
  labels:
    app: simple-echo-golang
spec:
  selector:
    matchLabels:
      app: simple-echo-golang
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-echo-golang
        group: inventory
        team: inventory
        app-language: golang
        app-type: backend
    spec:
      terminationGracePeriodSeconds: 75
      containers:
        - name: simple-echo-golang
          image: simple-echo-golang-image
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 1323
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
          envFrom:
            - configMapRef:
                name: generic-config
            - secretRef:
                name: simple-echo-golang
      imagePullSecrets:
        - name: gitlab-registry
