apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- patch.yaml

configMapGenerator:
- behavior: create
  envs:
  - secret/config.yaml
  name: RPC_NAME-config-env

resources:
- ../../../../base/RPC_PROJ/RPC_NAME
