apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus-clusterRole.yaml
- prometheus-clusterRoleBinding.yaml
- prometheus-networkPolicy.yaml
- prometheus-podDisruptionBudget.yaml
- prometheus-prometheus.yaml
- prometheus-prometheusRule.yaml
- prometheus-roleBindingConfig.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleConfig.yaml
- prometheus-roleSpecificNamespaces.yaml
- prometheus-service.yaml
- prometheus-serviceAccount.yaml
- prometheus-serviceMonitor.yaml
- prometheus-pvc.yaml