apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  redis.server: argocd-redis:6379
  server.insecure: "true"
  controller.diff.server.side: "true" # Comment if not set annotation in application -> argocd.argoproj.io/compare-options: ServerSideDiff=true
