apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  dex.config: |
    connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://gitlab.com
        clientID: $argocd-config-credential:clientID
        clientSecret: $argocd-config-credential:clientSecret
        useLoginAsID: false
  url: http://argo-cd.futuresky.co.th
  # exec.enabled: "true" # Enable exec console
