apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inventory
resources:
- ../../config
- namespace.yaml
- simple-echo-golang
images:
- name: simple-echo-golang-image
  newName: sannonthachai/simple-echo-golang
  newTag: latest