apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: create
  envs:
  - configmap.yaml
  name: tsb-dash-api-config-env

resources:
  - ../../../../../base/services/ea-cloud/tsb-dash-api
