apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: simple-echo-golang
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: inventory # namespace
  path: simple-echo-golang
  refreshAfter: 60s
  destination:
    name: simple-echo-golang
    create: true