apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-echo-golang-hpa
  namespace: poc-auto-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-echo-golang
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metric:
        name: simple_echo_requests_per_second
      target:
        type: AverageValue
        averageValue: "10"  # 10 RPS per pod
