apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tsb-dash-api-secret-env
spec:
  vaultAuthRef: ea-cloud
  type: kv-v2
  mount: ea-cloud
  path: tsb-dash-api
  refreshAfter: 60s
  destination:
    name: tsb-dash-api-secret-env
    create: true