kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: tsb-mw-fn-ingress
  annotations:
    nginx.ingress.kubernetes.io/compress-types: "text/css application/javascript application/json"
    nginx.ingress.kubernetes.io/compress-enable: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 50m
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 50m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  ingressClassName: nginx
  rules:
    - host: hmw.thaismilebus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tsb-mw-fn
                port:
                  number: 1323
