apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-registry
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: inventory
  path: docker
  refreshAfter: 60s
  destination:
    name: gitlab-registry
    create: true
    type: "kubernetes.io/dockerconfigjson"