apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
data:
  log.level: info
  git.commit-message-template: |
    build: automatic update of {{ .AppName }}
    {{ range .AppChanges -}}
    updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}
  registries.conf: |
    registries:
    - name: GitLab Container Registry
      api_url: http://192.168.12.101:5050
      prefix: 192.168.12.101:5050
      ping: yes
      insecure: true
      credentials: pullsecret:argocd/docker-register-pull-secret
