apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-deployed.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-health-degraded.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ea-cloud-argo-cd-status
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 32.3.5
    helm:
      valuesObject:
        controller:
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          persistence:
            storageClass: "longhorn"
            size: 3Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
