apiVersion: v1
kind: Service
metadata:
  name: simple-echo-golang
  labels:
    app: simple-echo-golang
spec:
  type: ClusterIP
  ports:
  - name: http-port
    port: 80
    targetPort: 1323
  selector:
    app: simple-echo-golang
