apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poc-auto-scaler
resources:
- ingresses
# - secrets
# - service-accounts
# - vault-auth
- simple-echo-golang
# - hpa
images:
- name: simple-echo-golang-image
  newName: registry.gitlab.com/ea-gitops/simple-echo-golang/dev
  newTag: 51988cfe
