apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
data:
  config.yaml: |
    logLevel: warn
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        elasticsearch:
          hosts:
            - # IP
          index: kube-events
          indexFormat: "kube-events-{2006-01-02}"