apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    # notifications.argoproj.io/subscribe.on-deployed.slack: # Slack Chanel
    # notifications.argoproj.io/subscribe.on-health-degraded.slack: # Slack Chanel
    # notifications.argoproj.io/subscribe.on-sync-failed.slack: # Slack Chanel
    argocd-image-updater.argoproj.io/service1.kustomize.image-name: simple-echo-golang-image
    argocd-image-updater.argoproj.io/service1.update-strategy: newest-build
    argocd-image-updater.argoproj.io/service1.allow-tags: regexp:^dev-.*
    argocd-image-updater.argoproj.io/image-list: service1=sannonthachai/simple-echo-golang
    argocd-image-updater.argoproj.io/git-branch: dev
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: inventory
  project: default
  source:
    path: overlays/services/inventory/overlay
    repoURL: http://192.168.242.46/gitops/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
