# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

resources:
- manager.yaml

