apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-notifications-secret
spec:
  vaultAuthRef: argocd
  type: kv-v2
  mount: argocd
  path: argocd-notifications
  refreshAfter: 60s
  destination:
    name: argocd-notifications-secret
    create: false