apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: 
        clientSecret: 
        orgs:
        - name: "DataMorph Collective"
  url: # Url to argocd
  # exec.enabled: "true" # Enable exec console
