apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: inventory
  namespace: argocd
spec:
  sourceRepos:
  - # Url to gitops repository
  destinations:
  - namespace: inventory
    server: https://kubernetes.default.svc