apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: redis
  name: redis-secret-env
spec:
  vaultAuthRef: redis
  type: kv-v2
  mount: system
  path: redis
  refreshAfter: 60s
  destination:
    name: redis-secret-env
    create: true