apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: development
  source:
    path: overlays/test
    repoURL: # Url to gitops repository
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - Prune=False
