apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: http://192.168.242.46/gitops/gitops.git
  username: 
  password: 
  insecure: "true" # Ignore validity of server's TLS certificate. Defaults to "false"
  type: git
  project: default
  name: gitlab