apiVersion: v1
kind: Service
metadata:
  name: tsb-dash-api
  labels:
    app: tsb-dash-api
spec:
  type: ClusterIP
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
  selector:
    app: tsb-dash-api
