apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- ../../../../base/systems/descheduler

patchesStrategicMerge:
- configmap.yaml

images:
- name: descheduler
  newName: registry.k8s.io/descheduler/descheduler
  newTag: v0.31.0