apiVersion: v1
kind: Secret
metadata:
  name: vault-script-secret
  namespace: vault-secrets-operator-system
type: Opaque
stringData:
  vault.sh: |
    #!/bin/bash
    set -euo pipefail

    REVIEWER_JWT="$(kubectl create token vso-sa --namespace vault-secrets-operator-system)"
    CA_CERT_PATH="/tmp/ca.crt"

    # Extract Kubernetes cluster CA
    kubectl get cm kube-root-ca.crt \
      -n kube-system \
      -o jsonpath="{['data']['ca\.crt']}" > ${CA_CERT_PATH}

    # Update Vault config
    curl --fail --silent --show-error \
      --header "X-Vault-Token: ${VAULT_TOKEN}" \
      --request POST \
      --data @- \
      ${VAULT_ADDR}/v1/auth/kubernetes/config <<EOF
    {
      "token_reviewer_jwt": "$(echo "${REVIEWER_JWT}" | sed 's/"/\\"/g')",
      "kubernetes_host": "${K8S_HOST}",
      "kubernetes_ca_cert": "$(awk '{printf "%s\\n", $0}' ${CA_CERT_PATH})"
    }
    EOF

    echo "Updated Vault kubernetes config at $(date)"
