apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

secretGenerator:
  - name: additional-scrape-configs
    files:
      - additional-scrape-configs.yaml

generatorOptions:
  disableNameSuffixHash: true
