apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: tsb-mw-fn
  labels:
    app: tsb-mw-fn
spec:
  selector:
    matchLabels:
      app: tsb-mw-fn
  replicas: 1
  template:
    metadata:
      labels:
        app: tsb-mw-fn
        group: tsb
        team: devops
        app-language: golang
        app-type: backend
    spec:
      terminationGracePeriodSeconds: 75
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: tsb-mw-fn
          image: tsb-mw-fn-image
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 1323
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
          resources:
            requests:
              cpu: "3m"
              memory: "50Mi"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: GROUP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['group']
          envFrom:
            - configMapRef:
                name: tsb-mw-fn-config-env
            - secretRef:
                name: tsb-mw-fn-secret-env
