apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kowl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    notifications.argoproj.io/subscribe.on-deployed.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-health-degraded.slack: ea-cloud-argo-cd-status
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ea-cloud-argo-cd-status
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  project: default
  source:
    chart: kowl
    repoURL: https://raw.githubusercontent.com/cloudhut/charts/master/archives
    targetRevision: 2.3.1
    helm:
      valuesObject:
        kowl:
          config:
            kafka:
              brokers:
                - kafka:9092
              sasl:
                enabled: true
                username: user1
        secret:
          existingSecret: kowl-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
