apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-auth
spec:
  vaultAuthRef: ea-cloud
  type: kv-v2
  mount: ea-cloud
  path: gitlab
  refreshAfter: 60s
  destination:
    name: gitlab-auth
    create: true
    type: "kubernetes.io/dockerconfigjson"