apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: additional-scrape-configs.yaml
  volumes:
  - name: pvc-prometheus-k8s
    persistentVolumeClaim:
      claimName: pvc-prometheus-k8s
  retention: 2d
  replicas: 1