---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "DefaultEvictor"
          args:
            nodeFit: true
        - name: "RemoveDuplicates"
          args:
            namespaces:
              exclude:
              - "cattle-fleet-system"
              - "cattle-impersonation-system"
              - "cattle-logging-system"
              - "cattle-system"
              - "kube-node-lease"
              - "kube-public"
              - "kube-system"
              - "longhorn-system"
        - name: "RemovePodsViolatingInterPodAntiAffinity"
          args:
            namespaces:
              exclude:
              - "cattle-fleet-system"
              - "cattle-impersonation-system"
              - "cattle-logging-system"
              - "cattle-system"
              - "kube-node-lease"
              - "kube-public"
              - "kube-system"
              - "longhorn-system"
        - name: "RemovePodsViolatingNodeAffinity"
          args:
            namespaces:
              exclude:
              - "cattle-fleet-system"
              - "cattle-impersonation-system"
              - "cattle-logging-system"
              - "cattle-system"
              - "kube-node-lease"
              - "kube-public"
              - "kube-system"
              - "longhorn-system"
            nodeAffinityType:
            - "requiredDuringSchedulingIgnoredDuringExecution"
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu": 30
              "memory": 30
            targetThresholds:
              "cpu": 50
              "memory": 50
            evictableNamespaces:
              exclude:
              - "cattle-fleet-system"
              - "cattle-impersonation-system"
              - "cattle-logging-system"
              - "cattle-system"
              - "kube-node-lease"
              - "kube-public"
              - "kube-system"
              - "longhorn-system"
        plugins:
          deschedule:
            enabled:
              - "RemovePodsViolatingInterPodAntiAffinity"
              - "RemovePodsViolatingNodeAffinity"
          balance:
            enabled:
              - "LowNodeUtilization"
              - "RemoveDuplicates"
