apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/systems/argocd-image-updater

patchesStrategicMerge:
# - container-image-pull-secret.yaml
- argocd-image-updater-cm.yaml
