apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ea-cloud
resources:
- ingresses
- secrets
- service-accounts
- vault-auth
- tsb-dash-api
- tsb-dashboard
- tsb-mw-fn
images:
- name: tsb-mw-fn-image
  newName: registry.gitlab.com/ea-dev/tsb-mw-fn/dev
  newTag: 5c1178ed
- name: tsb-dash-api-image
  newName: registry.gitlab.com/ea-dev/tsb-dash-api/dev
  newTag: 8ccd78d8
- name: tsb-dashboard-image
  newName: registry.gitlab.com/ea-dev/tsb-dashboard/dev
  newTag: bdc6746e
- name: tsb-mw-fn/dev
  newName: registry.gitlab.com/ea-dev/tsb-mw-fn/dev
  newTag: d5f5cbc1
- name: tsb-dash-api/dev
  newName: registry.gitlab.com/ea-dev/tsb-dash-api/dev
  newTag: 8ccd78d8
- name: tsb-dashboard/dev
  newName: registry.gitlab.com/ea-dev/tsb-dashboard/dev
  newTag: bdc6746e
