apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: # Slack Chanel
    notifications.argoproj.io/subscribe.on-health-degraded.slack: # Slack Chanel
    notifications.argoproj.io/subscribe.on-sync-failed.slack: # Slack Chanel
spec:
  destination:
    server: https://kubernetes.default.svc
  project: system
  source:
    path: overlays/system
    repoURL: # Url to gitops repository
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - Prune=False
