apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
  # annotations:
  #   notifications.argoproj.io/subscribe.on-deployed.slack: # Slack Chanel
  #   notifications.argoproj.io/subscribe.on-health-degraded.slack: # Slack Chanel
  #   notifications.argoproj.io/subscribe.on-sync-failed.slack: # Slack Chanel
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/systems
    repoURL: http://192.168.242.46/gitops/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - Prune=False
