apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- configmaps/argocd-cm.yaml
- configmaps/argocd-cmd-params-cm.yaml
- configmaps/argocd-notifications-cm.yaml
- configmaps/argocd-rbac-cm.yaml
- deployments/argocd-server.yaml
# - secrets/argocd-notifications-secret.yaml
- services/argocd-server.yaml
- statefulsets/argocd-application-controller.yaml

resources:
- ../../../base/argo-cd